networks:
  goald-mesh:
    driver: bridge

services:
  ms-registry:
    build: ./ms-registry
    ports:
      - "8761:8761"
    volumes:
      - ./:/telemetry
    networks:
      - goald-mesh
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5

  ms-gateway:
    build: ./ms-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./:/telemetry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-registry:8761/eureka/
    depends_on:
      ms-registry:
        condition: service_healthy
    networks:
      - goald-mesh

  ms-treatment:
    build: ./ms-treatment
    ports:
      - "8081-8085:8080" # Range de portas: Permite escalar até 5 réplicas sem conflito
    volumes:
      - ./:/telemetry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-registry:8761/eureka/
    depends_on:
      ms-registry:
        condition: service_healthy
    networks:
      - goald-mesh

  ms-emergency:
    build: ./ms-emergency
    ports:
      - "8086-8090:8080" # Range de portas: Permite escalar até 5 réplicas sem conflito
    volumes:
      - ./:/telemetry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-registry:8761/eureka/
    depends_on:
      ms-registry:
        condition: service_healthy
    networks:
      - goald-mesh

  ms-monitor:
    build: ./ms-monitor
    ports:
      - "8091-8095:8080" # Range de portas: Permite escalar até 5 réplicas sem conflito
    volumes:
      - ./:/telemetry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-registry:8761/eureka/
    depends_on:
      ms-registry:
        condition: service_healthy
    networks:
      - goald-mesh

  ms-intelligence:
    build: ./ms-intelligence
    volumes:
      - ./:/telemetry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-registry:8761/eureka/
    depends_on:
      ms-registry:
        condition: service_healthy
    networks:
      - goald-mesh