server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # I am the server, do not register me
    fetchRegistry: false      # I am the server, do not fetch from myself
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/