server:
  port: 8084

spring:
  application:
    name: ms-emergency

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: "TAS Emergency Service"
    description: "GoalD Emergency Notification Subsystem"

logging:
  level:
    agent: DEBUG
    org.springframework.web: INFO