server:
  port: 8081

spring:
  application:
    name: ms-monitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info