server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: goald-service-route
          uri: lb://MS-INTELLIGENCE
          predicates:
            - Path=/**
          filters:
            # Aciona o Disjuntor e redireciona para o Fallback em caso de erro/timeout
            - name: CircuitBreaker
              args:
                name: adaptationCircuitBreaker
                fallbackUri: forward:/fallback

# Configuração da Adaptação (Métrica do Circuit Breaker)
resilience4j:
  circuitbreaker:
    instances:
      adaptationCircuitBreaker:
        slidingWindowSize: 10        # Avalia as últimas 10 requisições
        failureRateThreshold: 50     # Se 50% falhar, abre o circuito
        waitDurationInOpenState: 10s # Espera 10s antes de tentar rotear de novo

eureka:
  client:
    service-url:
      defaultZone: http://ms-registry:8761/eureka/
  instance:
    prefer-ip-address: true